[package]
name = "swmr-cell"
version = "0.3.1"
edition = "2024"
authors = ["Shao G. <shaogme@gmail.com>"]
description = "A thread-safe single-writer multi-reader cell with wait-free reads and version-based garbage collection"
license = "MIT OR Apache-2.0"
repository = "https://github.com/shaogme/swmr-cell"
homepage = "https://github.com/shaogme/swmr-cell"
documentation = "https://docs.rs/swmr-cell"
keywords = ["swmr", "wait-free", "rcu", "concurrency", "lock-free"]
categories = ["concurrency", "data-structures", "memory-management"]

[dependencies]
spin = { version = "0.10", optional = true }
loom = { version = "0.7", optional = true }
swmr-barrier = "0.1.4"


[features]
default = ["std"]
std = []
loom = ["dep:loom", "swmr-barrier/loom"]
